### ISSUE TITLE
AdGuardHome 使用问题

### ISSUE THREAD

**Issue by 1379** [hezhijie0327/GFWList2AGH#1]
我不太清楚如何使用这个项目，请问这是一个Adguradhome dns分流的脚本吗？具体如何在Adguradhome 里使用呢

**Comment by 1379** [comment]
或者有个Readme也可以啊🤣

**Comment by hezhijie0327** [comment]
是的 我把教程放在自己的网站上了位置在[这里](https://www.zhijie.online/resources/personal_projects/GFWList2AGH/page.html)
![Xnip2020-08-19_20-08-48](https://user-images.githubusercontent.com/58100052/90633003-dc0b9480-e257-11ea-8e36-5aefc6054a56.jpg)

**Comment by 1379** [comment]
感谢，已star。另外，想问一下，这些域名是作者根据https://github.com/gfwlist/gfwlist用脚本生成的吗？

**Comment by hezhijie0327** [comment]
是的

CNACC域名来自：Loyalsoldier/v2ray-rules-dat，felixonmars/dnsmasq-china-list
GFWList域名来自：Loukky/gfwlist-by-loukky，gfwlist/gfwlist，poctopus/gfwlist-plus，Loyalsoldier/cn-blocked-domain，Loyalsoldier/v2ray-rules-dat，cokebar/gfwlist2dnsmasq，pexcn/gfwlist-extras

从中提取域名后通过我自己的[另一个项目](https://github.com/hezhijie0327/DHDb)移除无效域名后生成的

**Comment by 1379** [comment]
ok，再次感谢！
