### ISSUE TITLE
blocklist

### ISSUE THREAD

**Issue by Atroc-0625** [hezhijie0327/GFWList2AGH#11]
你好，要如何自定义去除gfw域名，比如想要去除/apple.com/

**Comment by hezhijie0327** [comment]
1. 目前比较偷懒的方法就是把它添加到 `cnacc` 中
2. 或者设计一个移除某条规则的方法，暂定`!example.org`

**Comment by Atroc-0625** [comment]
我觉得可以在写两个文件data下，就是排除cnacc或者gfwlist，这样更加自定义且方便。

**Comment by Atroc-0625** [comment]
或者您说的第二条也不错。!example.org强制取消域名添加在规则列表域名中。

**Comment by hezhijie0327** [comment]
1. 已支持强制移除，例如：`!example.org`
2. 优先级：`!example.org` > `@example.org` > `example.org`

**Comment by Atroc-0625** [comment]
好的，辛苦，多谢。

**Comment by Atroc-0625** [comment]
感觉有些问题，连/google.com/都不在gfwlist中了。

**Comment by Atroc-0625** [comment]
还有/apple.com/也不在了。

**Comment by hezhijie0327** [comment]
已修复

**Comment by Atroc-0625** [comment]
gfwlist有添加两个/appsto.re/

**Comment by Atroc-0625** [comment]
/icloud.com/也是，感觉重复的域名没有过滤赶紧

**Comment by Atroc-0625** [comment]
/icloud-content.com/
/itunes.com/
/icloud-content.com/
/me.com/

**Comment by hezhijie0327** [comment]
1. 已修复
2. 我的问题，修复上面问题后忘记把去重步骤放进去了

**Comment by Atroc-0625** [comment]
好的，已经好了，辛苦。
