### ISSUE TITLE
adfilter_domain

### ISSUE THREAD

**Issue by Atroc-0625** [hezhijie0327/GFWList2AGH#13]
你好，个人觉得没必要加入去广告，dns解析就是解析，去广告应该用专业工具去除。

**Comment by hezhijie0327** [comment]
广告域名解析还是正常解析并没有进行拦截，只是将已知的广告域名走默认 `DNS` 而不再走分流步骤以减少文件大小（`-0.1M`）

**Comment by Atroc-0625** [comment]
那如果广告域名解析是被污染域名，那就解析出错误的地址，没必要刻意去减少文件大小，就1.6.7的脚本生成的规则域名，处理解析速度都不会慢。

**Comment by Atroc-0625** [comment]
在脚本1.6.8我看移除了一些规则，那以后规则域名是否全面呢。

**Comment by hezhijie0327** [comment]
> 那如果广告域名解析是被污染域名，那就解析出错误的地址，没必要刻意去减少文件大小，就1.6.7的脚本生成的规则域名，处理解析速度都不会慢。

已回滚


> 在脚本1.6.8我看移除了一些规则，那以后规则域名是否全面呢。

1. 现有规则 [hezhijie0327/V2SiteDAT](https://github.com/hezhijie0327/V2SiteDAT) 由`geosite.dat`生成，包含了部分被移除的正确规则
2. 现有规则比原有规则更全，将所有已被分类的域名进行展开，如在复合规则中提取`@cn`标签加入至 `cnacc`。
3. 移除原因：规则中存在复合规则，在`cnacc`中存在非国内域名，如：在[icloud.txt](https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/icloud.txt)中存在 `icloud.jp` 与 `icloud.com.cn` 共存的现象

**Comment by hezhijie0327** [comment]
当前 [hezhijie0327/V2SiteDAT](https://github.com/hezhijie0327/V2SiteDAT) 解析 `geosite.dat` 流程：
1. 文件名为`category-*-cn, cn, geolocation-cn`存入 `cnacc`
2. 其余`category-*, geolocation!-cn`存入 `gfwlist`，如果其规则内包含`@cn`标签则将该规则存入 `cnacc`

**Comment by Atroc-0625** [comment]
对的，确实应该展开，那么移出ad域名即可。

**Comment by Atroc-0625** [comment]
你的意思如果在gfw中出现@cn顶级域名，强制写入!cn

**Comment by hezhijie0327** [comment]
该情况仅会出现在`category-*`中，如在[`category-games`](https://github.com/v2fly/domain-list-community/blob/master/data/category-games)中的[`steam`](https://github.com/v2fly/domain-list-community/blob/master/data/steam)。其中`@cn`标签将被放入`cnacc`，其余放入`gfwlist`。
