### ISSUE TITLE
域名格式需求

### ISSUE THREAD

**Issue by Atroc-0625** [hezhijie0327/GFWList2AGH#14]
你好，可以在生成一个域名列表吗？域名的格式作为图片这种的。
![image](https://user-images.githubusercontent.com/37469514/104806522-14b59700-5813-11eb-953a-aa0ad5baaf64.png)

**Comment by Atroc-0625** [comment]
就是纯域名
aaa.com
bbb.com
ccc.com
ddd.com

**Comment by hezhijie0327** [comment]
`lite` 列表就是纯一级域名列表
<img width="297" alt="截图 2021-01-16 18 44 36" src="https://user-images.githubusercontent.com/58100052/104809812-e80d7980-582a-11eb-90c1-2ddfd528984e.png">
Duplicate of #4.

**Comment by Atroc-0625** [comment]
是域名的排版格式，
aaa.com
bbb.com
ccc.com
这样生成排版

**Comment by hezhijie0327** [comment]
类似[这样](https://raw.githubusercontent.com/hezhijie0327/V2SiteDAT/main/proxy.txt)的嘛？
<img width="567" alt="截图 2021-01-16 19 06 33" src="https://user-images.githubusercontent.com/58100052/104810170-f9a45080-582d-11eb-971e-43c5eee810a4.png">

**Comment by Atroc-0625** [comment]
是的

**Comment by Atroc-0625** [comment]
就是体现出纯域名，在国内和国外分别新建两个文件

**Comment by Atroc-0625** [comment]
如果可以的话，还可以做个支持smart 的配置文件，可以的话CN这个定义名可以自行修改一下
![image](https://user-images.githubusercontent.com/37469514/104810341-d9c15c80-582e-11eb-9acf-6c3170998605.png)

**Comment by Atroc-0625** [comment]
因为您的脚本很好，所以希望此项目可以可以不局限于AGH

**Comment by Atroc-0625** [comment]
dnsdnsmasq也可以支持一下

**Comment by Atroc-0625** [comment]
您的脚本优点在于，可以自定义添加排除自己指定的域名，合并多个项目收集的国内域名和国外域名，并去重复等一些操作，很实用。

**Comment by hezhijie0327** [comment]
1. 已支持生成 `raw` 列表；默认不自动生成，需手动将代码取消注释。
<img width="1041" alt="截图 2021-01-16 20 33 09" src="https://user-images.githubusercontent.com/58100052/104811980-0fb80e00-583a-11eb-88d3-3e7e84471311.png">

> 如果可以的话，还可以做个支持smart 的配置文件，可以的话CN这个定义名可以自行修改一下

> dnsdnsmasq也可以支持一下

这两点后续也会和 `raw` 列表一致，默认不自动生成

**Comment by Atroc-0625** [comment]
split的区别是什么？

**Comment by hezhijie0327** [comment]
1. `split` 结尾是指纯`白名单`或`黑名单`模式
2. 非 `split` 结尾将`黑白名单`结合。修正单个列表中存在的复合问题，如：`fonts.googleapis.com` 与其他 `googleapis.com`，前者在国内有 `CDN`，其余走国外 `DNS`。

**Comment by Atroc-0625** [comment]
所以用黑白名单结合会好一些吗？

**Comment by hezhijie0327** [comment]
嗯

**Comment by Atroc-0625** [comment]
黑白名单结合配置文件有些问题
中间应该去除上游dns，头部已经有了。
![image](https://user-images.githubusercontent.com/37469514/104812421-f5cbfa80-583c-11eb-80fb-2f8a7f5e56cd.png)

**Comment by hezhijie0327** [comment]
这应该是刚刚那波改动导致，我稍后修复一下

**Comment by Atroc-0625** [comment]
]#的意思是规则内会遵守默认的dns上游查询对吗？
如果用黑白名单结合模式，AGH的处理能力，解析速度会有所保障吗？

**Comment by Atroc-0625** [comment]
smartdns和dnsdnsmasq的配置文件是在计划中吗？

**Comment by hezhijie0327** [comment]
> ]#的意思是规则内会遵守默认的dns上游查询对吗？
对的

> 如果用黑白名单结合模式，AGH的处理能力，解析速度会有所保障吗？
使用下来没啥影响
<img width="587" alt="截图 2021-01-16 21 01 56" src="https://user-images.githubusercontent.com/58100052/104812562-16e11b00-583e-11eb-897c-c81d224f7f78.png">


> smartdns和dnsdnsmasq的配置文件是在计划中吗？
是的，可能在明后两天内，今天有点事情

**Comment by Atroc-0625** [comment]
好的，辛苦，希望能尽快修复bug,我好使用黑白名单结合模式进行测试。

**Comment by hezhijie0327** [comment]
嗯，可以先使用先前的 [commit](https://github.com/hezhijie0327/GFWList2AGH/tree/3cbb80d5933a0ae7054a8e84157b4ee4fe31d508) 3cbb80d5933a0ae7054a8e84157b4ee4fe31d508 做测试

**Comment by Atroc-0625** [comment]
今晚会修复好吗？如果可以，我等待新的脚本。

**Comment by hezhijie0327** [comment]
嗯

**Comment by Atroc-0625** [comment]
你好，今晚还会修复bug吗？

**Comment by hezhijie0327** [comment]
在修，现在在找出错的原因

**Comment by hezhijie0327** [comment]
目前屏蔽生成 “`split`” 列表，就这块仍有问题

**Comment by hezhijie0327** [comment]
已修复 335dd5c46ddeb508d17af0624d18c18494fef383

**Comment by Atroc-0625** [comment]
好的，辛苦，已经修复了。

**Comment by Atroc-0625** [comment]
upstream_dns_file: /root/AdGuardHome/gfwlist2agh_blacklist_full.txt
不知道为什么换成了黑白名单结合模式，AGH就启动失败

**Comment by Atroc-0625** [comment]
2021/01/17 11:55:16 [info] AdGuard Home, version 0.105.0-beta.2, channel beta, arch linux amd64
2021/01/17 11:55:16 [info] Configuration file is OK

**Comment by Atroc-0625** [comment]
● AdGuardHome.service - AdGuard Home: Network-level blocker
   Loaded: loaded (/etc/systemd/system/AdGuardHome.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2021-01-17 11:55:25 CST; 9s ago
  Process: 4732 ExecStart=/root/AdGuardHome/AdGuardHome -s run (code=exited, status=1/FAILURE)
 Main PID: 4732 (code=exited, status=1/FAILURE)

Jan 17 11:55:25 localhost.localdomain systemd[1]: Unit AdGuardHome.service entered failed state.
Jan 17 11:55:25 localhost.localdomain systemd[1]: AdGuardHome.service failed.

**Comment by hezhijie0327** [comment]
1. 我这刚刚测试了下黑 / 白名单均能正常运行
2. 试着运行 `/root/AdGuardHome/AdGuardHome -v` 查看报错原因，注：先将进程结束后再运行

**Comment by Atroc-0625** [comment]
2021/01/17 12:02:54 10435#1 [info] AdGuard Home, version 0.105.0-beta.2, channel beta, arch linux amd64
2021/01/17 12:02:54 10435#1 [debug] Current working directory is /root/AdGuardHome
2021/01/17 12:02:54 10435#1 [debug] github.com/AdguardTeam/AdGuardHome/internal/home.upgradeConfig(): got schema version 7
2021/01/17 12:02:54 10435#1 [debug] Reading config file: /root/AdGuardHome/AdGuardHome.yaml
2021/01/17 12:02:54 10435#1 [debug] AutoHosts: loading hosts from file /etc/hosts
2021/01/17 12:02:54 10435#1 [debug] AutoHosts: added 127.0.0.1 -> localhost
2021/01/17 12:02:54 10435#1 [debug] AutoHosts: added reverse-address 127.0.0.1 -> localhost
2021/01/17 12:02:54 10435#1 [debug] AutoHosts: added 127.0.0.1 -> localhost.localdomain
2021/01/17 12:02:54 10435#1 [debug] AutoHosts: added reverse-address 127.0.0.1 -> localhost.localdomain
2021/01/17 12:02:54 10435#1 [debug] AutoHosts: added 127.0.0.1 -> localhost4
2021/01/17 12:02:54 10435#1 [debug] AutoHosts: added reverse-address 127.0.0.1 -> localhost4
2021/01/17 12:02:54 10435#1 [debug] AutoHosts: added 127.0.0.1 -> localhost4.localdomain4
2021/01/17 12:02:54 10435#1 [debug] AutoHosts: added reverse-address 127.0.0.1 -> localhost4.localdomain4
2021/01/17 12:02:54 10435#1 [debug] AutoHosts: added ::1 -> localhost
2021/01/17 12:02:54 10435#1 [debug] AutoHosts: added reverse-address ::1 -> localhost
2021/01/17 12:02:54 10435#1 [debug] AutoHosts: added ::1 -> localhost.localdomain
2021/01/17 12:02:54 10435#1 [debug] AutoHosts: added reverse-address ::1 -> localhost.localdomain
2021/01/17 12:02:54 10435#1 [debug] AutoHosts: added ::1 -> localhost6
2021/01/17 12:02:54 10435#1 [debug] AutoHosts: added reverse-address ::1 -> localhost6
2021/01/17 12:02:54 10435#1 [debug] AutoHosts: added ::1 -> localhost6.localdomain6
2021/01/17 12:02:54 10435#1 [debug] AutoHosts: added reverse-address ::1 -> localhost6.localdomain6
2021/01/17 12:02:54 10435#1 [debug] clients: removed 0 client aliases
2021/01/17 12:02:54 10435#1 [debug] Clients: added 0 client aliases from DHCP
2021/01/17 12:02:54 10435#1 [debug] Writing YAML file: /root/AdGuardHome/AdGuardHome.yaml
2021/01/17 12:02:54 10435#1 [info] Initializing auth module: /root/AdGuardHome/data/sessions.db
2021/01/17 12:02:54 10435#1 [debug] Auth: loaded 5 sessions from DB (removed 0 expired)
2021/01/17 12:02:54 10435#1 [info] Auth: initialized.  users:1  sessions:5
2021/01/17 12:02:54 10435#1 [debug] github.com/AdguardTeam/AdGuardHome/internal/home.verifyCertChain(): TLS: got certificate: 3449 bytes
2021/01/17 12:02:54 10435#1 [info] number of certs - 2
2021/01/17 12:02:54 10435#1 [info] got an intermediate cert
2021/01/17 12:02:54 10435#1 [info] Initialize web module
2021/01/17 12:02:54 10435#1 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.(*statsCtx).dbOpen(): db.Open...
2021/01/17 12:02:54 10435#1 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.(*statsCtx).dbOpen(): db.Open
2021/01/17 12:02:54 10435#1 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.(*statsCtx).beginTxn(): db.Begin...
2021/01/17 12:02:54 10435#1 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.(*statsCtx).beginTxn(): db.Begin
2021/01/17 12:02:54 10435#1 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.createObject(): Deleting old units...
2021/01/17 12:02:54 10435#1 [debug] Stats: initialized
2021/01/17 12:02:54 10435#1 [debug] DNS: added 0 A/PTR entries from DHCP
2021/01/17 12:02:54 10435#1 [debug] IPSET: added 0 hosts
2021/01/17 12:02:54 10435#1 [debug] DNS: using 4 upstream servers from file /root/AdGuardHome/gfwlist2agh_blacklist_full.txt
2021/01/17 12:02:54 10435#1 [debug] Bootstraps: [1.1.1.1 8.8.8.8 208.67.222.222]
2021/01/17 12:02:54 10435#1 [debug] Upstream 0: tls://dns.pub:853
2021/01/17 12:02:54 10435#1 [debug] Upstream 1: tls://dns.alidns.com:853
2021/01/17 12:02:54 10435#1 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.(*statsCtx).beginTxn(): db.Begin...
2021/01/17 12:02:54 10435#1 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.(*statsCtx).beginTxn(): db.Begin
2021/01/17 12:02:54 10435#1 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.(*statsCtx).flushUnitToDB(): Flushing unit 447460
2021/01/17 12:02:54 10435#1 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.(*statsCtx).commitTxn(): tx.Commit
2021/01/17 12:02:54 10435#1 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.(*statsCtx).Close(): db.Close...
2021/01/17 12:02:54 10435#1 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.(*statsCtx).Close(): db.Close
2021/01/17 12:02:54 10435#1 [debug] Stats: closed
2021/01/17 12:02:54 10435#1 [debug] querylog: there's nothing to write to a file
2021/01/17 12:02:54 10435#1 [debug] Closed all DNS modules
2021/01/17 12:02:54 10435#1 [fatal] dnsServer.Prepare: dns: proxy.ParseUpstreamsConfig: wrong hostname specification: #akadns.net

**Comment by hezhijie0327** [comment]
1. 问题来自你修改的 [data_cnacc.txt](https://github.com/Atroc-0625/GFWList-AGH/blob/caadc23e1bb85e276e3fc67407196185a48ca41d/data/data_cnacc.txt#L46)
<img width="201" alt="截图 2021-01-17 12 06 42" src="https://user-images.githubusercontent.com/58100052/104830747-a2998c80-58bc-11eb-8309-ced5c68719ad.png">
2. `强制添加`功能可能有个隐藏的 `BUG` 😭

**Comment by Atroc-0625** [comment]
😹是有冲突吗？

**Comment by Atroc-0625** [comment]
46我已经注释了。

**Comment by Atroc-0625** [comment]
因为对于我来说，不管是google/apple域名只要在国内有备案的域名就可以使用国内dns进行解析，因为备案域名太多数都会使用cdn调度，所以必须要在国内进行解析。

**Comment by hezhijie0327** [comment]
理论上现在应该修复了，脚本更新下ecdebabb291b354aa58dae538d4aa6371ded3cf0

**Comment by Atroc-0625** [comment]
ok，我更新一下脚本。

**Comment by Atroc-0625** [comment]
你好，已经正常了，是什么因为原因导致，那么后面强制添加域名和排除域名功能是否可以正常使用呢。

**Comment by hezhijie0327** [comment]
1. `#` 符号强制添加 / 排除时未排除所导致的
2. 功能正常（当时测试时没测试`#@example.org` / `#!example.org`😭）

**Comment by Atroc-0625** [comment]
ok，已经完美，运行，我先运行个几天，看一下黑白名单的组合模式使用起来感觉如何。

**Comment by Atroc-0625** [comment]
你好，此国内域名列表，和国外域名列表是全网最全的吗？我看整合了几个域名规则。

**Comment by hezhijie0327** [comment]
1. 目前把能找到的都塞进去了,包括 `v2ray` 的 `geosite.dat`
2. 如果有其他可靠的列表可以再整合进去

**Comment by Atroc-0625** [comment]
我记得smartdns是conf文件。

**Comment by Atroc-0625** [comment]
> 1. 目前把能找到的都塞进去了,包括 `v2ray` 的 `geosite.dat`
> 2. 如果有其他可靠的列表可以再整合进去

在我印象中，您的规则是全网最全的了。

**Comment by Atroc-0625** [comment]
感觉项目名可以修改了，支持了conf文件就不单单是AGH可以使用了，也不单单只有gfwlist

**Comment by hezhijie0327** [comment]
1. 项目名暂时不考虑更改
2. 已支持生成简易的 `DNSMasq` 与 `SmartDNS` 规则，默认不自动生成
3. 可根据实际情况更改上游服务器或组名
<img width="1013" alt="截图 2021-01-17 13 41 43" src="https://user-images.githubusercontent.com/58100052/104832140-d62ee380-58c9-11eb-81b3-6708781d6645.png">

**Comment by Atroc-0625** [comment]
OK，感谢。
