### ISSUE TITLE
合并上游域名有问题。

### ISSUE THREAD

**Issue by Atroc-0625** [hezhijie0327/GFWList2AGH#15]
比如：
cl1-cdn.origin-apple.com.akadns.net
此域名在felixonmars/dnsmasq-china-list/master/apple.china.conf内，可是最后没有生成出来。

**Comment by Atroc-0625** [comment]
这样会导致有一些，apple在国内访问会更好的域名，无法加入进去，导致最后dns解析会有些问题。

**Comment by hezhijie0327** [comment]
1. 此问题原因已找到，来自上游规则 [Loyalsoldier/v2ray-rules-dat](https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/proxy-list.txt)，同 #8
<img width="392" alt="截图 2021-01-24 14 50 32" src="https://user-images.githubusercontent.com/58100052/105623371-38509100-5e54-11eb-9ce6-c9efbec696f7.png">

2. 生成规则时，由于`cnacc`与`gfwlist` 规则互不存在原则，故添加失败
3. 由于现版本存在 [hezhijie0327/V2SiteDAT](https://github.com/hezhijie0327/V2SiteDAT) 作为上游，稍后将`Loyalsoldier/v2ray-rules-dat`移除

**Comment by Atroc-0625** [comment]
你好，我的理解是，在full模式下，cnacc和gfwlist不能共同存在一个域名对吗？

**Comment by hezhijie0327** [comment]
1. 不，所有模式均不能同时存在
2. 如要添加就得使用`强制添加：@example.org`

**Comment by Atroc-0625** [comment]
那么移除Loyalsoldier/v2ray-rules-dat，会有什么影响

**Comment by hezhijie0327** [comment]
文件变动如 116328aafb1cd94a49232d550ee94396a9a3c55b 所示

**Comment by Atroc-0625** [comment]
这样的调整，那Loyalsoldier的规则就不会出现在规则列表内了，所以这个问题就是合并多个上游引起的问题？

**Comment by hezhijie0327** [comment]
1. 

> 所以这个问题就是合并多个上游引起的问题？

是的，同 #8 中`translate.baidu.com`也来自同一文件

2.


> 这样的调整，那Loyalsoldier的规则就不会出现在规则列表内了

但由于`Loyalsoldier/v2ray-rules-dat`同`hezhijie0327/V2SiteDAT`使用相同的`geosite.dat`文件，从规则完整性来讲，没啥影响。#12 #13

**Comment by Atroc-0625** [comment]
# 百度翻译 #8 - Loyalsoldier/v2ray-rules-dat//那这个可以删除了。

**Comment by hezhijie0327** [comment]
嗯

**Comment by Atroc-0625** [comment]
还是有问题 ，iadsdk.apple.com 这个域名还是没有加入进去。

**Comment by Atroc-0625** [comment]
phobos.apple.com

**Comment by Atroc-0625** [comment]
还是不全

**Comment by hezhijie0327** [comment]
1. 依旧是上游导致😭
2. 由于脚本已支持`base64`解密，故移除多余上游 [`cokebar/gfwlist2dnsmasq`](https://raw.githubusercontent.com/cokebar/gfwlist2dnsmasq/gh-pages/gfwlist_domain.txt)，脚本未将以下异常规则添入（不符合域名规则：`sed "s/http\:\/\///g;s/https\:\/\///g" | tr -d "|" | tr "A-Z" "a-z" | grep -E "^(([a-z]{1})|([a-z]{1}[a-z]{1})|([a-z]{1}[0-9]{1})|([0-9]{1}[a-z]{1})|([a-z0-9][-_\.a-z0-9]{1,61}[a-z0-9]))\.([a-z]{2,13}|[a-z0-9-]{2,30}\.[a-z]{2,3})$" | sort | uniq`）；以下规则将从 `felixonmars/dnsmasq-china-list` 及 `hezhijie0327/V2SiteDAT` 添入`cnacc`
3. 异常规则：`phobos.apple.com*/video` `iadsdk.apple.com`

**Comment by Atroc-0625** [comment]
那么这次调整会导致一些规则减少吗？

**Comment by hezhijie0327** [comment]
规则反而会变多，增加 `9` 条，详情 f20a6afbac1024008ed770294900044dad6a343c

**Comment by Atroc-0625** [comment]
我想问一下，hezhijie0327/V2SiteDAT的收集上游域名的原理还有dhdb_dead是用来做什么的。

**Comment by hezhijie0327** [comment]
1. `hezhijie0327/V2SiteDAT` 解析 v2ray 官方的 `geosite.dat` 文件并输出规则；将`本项目`及`hezhijie0327/AdFilter`数据合并为自定义的`geosite.dat` 文件
2. `dhdb_dead ` 仅移除无效域名，通过查询域名的 `A` 记录及 `AAAA` 记录

**Comment by Atroc-0625** [comment]
那为什么移除上游的规则就可以了，hezhijie0327/V2SiteDAT用的也是这个上游呀。

**Comment by hezhijie0327** [comment]
规则提取逻辑差异

**Comment by Atroc-0625** [comment]
nice。
