### ISSUE TITLE
增加对 Bind9 规则的支持

### ISSUE THREAD

**Issue by hezhijie0327** [hezhijie0327/GFWList2AGH#17]
可以加个bind的分流？？ @hezhijie0327

_Originally posted by @Potterli20 in https://github.com/hezhijie0327/GFWList2AGH/issues/16#issuecomment-771523097_

**Comment by Potterli20** [comment]
![图片](https://user-images.githubusercontent.com/28734349/106585330-2a9cb900-6582-11eb-9e9b-98f001a6f03e.png)

**Comment by hezhijie0327** [comment]
正在构建中，稍后请使用以下地址进行测试：
[blacklist_full.conf](https://source.zhijie.online/GFWList2AGH/main/gfwlist2bind9/blacklist_full.conf)
[blacklist_lite.conf](https://source.zhijie.online/GFWList2AGH/main/gfwlist2bind9/blacklist_lite.conf)
[whitelist_full.conf](https://source.zhijie.online/GFWList2AGH/main/gfwlist2bind9/whitelist_full.conf)
[whitelist_lite.conf](https://source.zhijie.online/GFWList2AGH/main/gfwlist2bind9/whitelist_lite.conf)

**Comment by Potterli20** [comment]
> 
> 
> 正在构建中，稍后请使用以下地址进行测试：
> [blacklist_full.conf](https://source.zhijie.online/GFWList2AGH/main/gfwlist2bind9/blacklist_full.conf)
> [blacklist_lite.conf](https://source.zhijie.online/GFWList2AGH/main/gfwlist2bind9/blacklist_lite.conf)
> [whitelist_full.conf](https://source.zhijie.online/GFWList2AGH/main/gfwlist2bind9/whitelist_full.conf)
> [whitelist_lite.conf](https://source.zhijie.online/GFWList2AGH/main/gfwlist2bind9/whitelist_lite.conf)

好的谢谢

**Comment by Potterli20** [comment]
> 
> 
> 正在构建中，稍后请使用以下地址进行测试：
> [blacklist_full.conf](https://source.zhijie.online/GFWList2AGH/main/gfwlist2bind9/blacklist_full.conf)
> [blacklist_lite.conf](https://source.zhijie.online/GFWList2AGH/main/gfwlist2bind9/blacklist_lite.conf)
> [whitelist_full.conf](https://source.zhijie.online/GFWList2AGH/main/gfwlist2bind9/whitelist_full.conf)
> [whitelist_lite.conf](https://source.zhijie.online/GFWList2AGH/main/gfwlist2bind9/whitelist_lite.conf)

bind9 是不支持doh吧？

**Comment by hezhijie0327** [comment]
均不支持

**Comment by Potterli20** [comment]
> 
> 
> 均不支持

gfwlist影响好大只能做中国分流
