### ISSUE TITLE
有什么办法去走，你写的脚本，你清楚。我怕写错脚本

### ISSUE THREAD

**Issue by Potterli20** [hezhijie0327/GFWList2AGH#18]
![图片](https://user-images.githubusercontent.com/28734349/106733888-5fc20d80-664d-11eb-9eab-658c1f491155.png)

**Comment by hezhijie0327** [comment]
意思是添加新域名，让其走 `doh.pub` 和 `dns.alidns.com` 是吗？

**Comment by Potterli20** [comment]
> 
> 
> 意思是添加新域名，让其走 `doh.pub` 和 `dns.alidns.com` 是吗？

是的

**Comment by hezhijie0327** [comment]
1. 国内域名添加入：[data_cnacc.txt](https://github.com/hezhijie0327/GFWList2AGH/blob/main/data/data_cnacc.txt) -> 走 `doh.pub` `dns.alidns.com`
2. 国外域名添加入：[data_gfwlist.txt](https://github.com/hezhijie0327/GFWList2AGH/blob/main/data/data_gfwlist.txt) -> 走 `doh.opendns.com` `dns.google`
3. 语法见文件内描述

**Comment by Potterli20** [comment]
> 
> 
> 意思是添加新域名，让其走 `doh.pub` 和 `dns.alidns.com` 是吗？

我在我的服务器把黑名单分流和白名单分流合并了，然后出现一写问题

**Comment by hezhijie0327** [comment]
> 我在我的服务器把黑名单分流和白名单分流合并了，然后出现一写问题

如果是 AGH 的话，默认构建时就存在黑白名单合并的列表：非 `split.txt` 结尾文件，如 [blacklist_full.txt](https://github.com/hezhijie0327/GFWList2AGH/blob/main/gfwlist2adguardhome/blacklist_full.txt)

**Comment by Potterli20** [comment]
> 
> 
> > 我在我的服务器把黑名单分流和白名单分流合并了，然后出现一写问题
> 
> 如果是 AGH 的话，默认构建时就存在黑白名单合并的列表：非 `split.txt` 结尾文件，如 [blacklist_full.txt](https://raw.githubusercontent.com/hezhijie0327/GFWList2AGH/main/gfwlist2adguardhome/blacklist_full.txt)

http://dns.trli.club/dns/dns-txt/gfwlist2adguardhome/domain_full.txt，这个就是我合并分流文件

**Comment by hezhijie0327** [comment]
1. 如果只是需要修改上游的话，只需修改 [release.sh](https://github.com/hezhijie0327/GFWList2AGH/blob/e9262a7168549cd30ad038ca21150c3bc8fb08b0/release.sh#L106) 中 `domestic_dns` 及 `foreign_dns` 键值
2. 上游过多会导致规则文件变大，构建时间变长
3. AGH 中 `#` 为保留键值，即意为使用默认上游服务器

**Comment by hezhijie0327** [comment]
我根据你配置文件中的配置，生成了此文件 [blacklist_full.txt](https://source.zhijie.online/GFWList2AGH/debug/gfwlist2adguardhome/blacklist_full.txt)

**Comment by Potterli20** [comment]
![图片](https://user-images.githubusercontent.com/28734349/106738579-107edb80-6653-11eb-8f1e-50486a721b9f.png)
我就是这样合并的

**Comment by hezhijie0327** [comment]
1. 不需要合并规则非`split`文件已经合并好了，`split`是为了特定人群需求才出的单独列表
2. `split` 文件（以黑名单为例）结构为：默认上游 DNS 服务器（国内DNS） +  黑名单规则（国外DNS）
3. 非 `split` 文件（以黑名单为例）结构为：默认上游 DNS 服务器（国内） + 白名单规则（#）+ 黑名单规则（国外DNS）

**Comment by Potterli20** [comment]
> 
> 
>     1. 不需要合并规则，非`split`文件已经合并好了，`split`是为了特定人群需求才出的单独列表
> 
>     2. `split` 文件（[以黑名单为例](https://source.zhijie.online/GFWList2AGH/main/gfwlist2adguardhome/blacklist_full_split.txt)）结构为：默认上游 DNS 服务器（国内DNS） +  黑名单规则（国外DNS）
> 
>     3. 非 `split` 文件（[以黑名单为例](https://source.zhijie.online/GFWList2AGH/main/gfwlist2adguardhome/blacklist_full.txt)）结构为：默认上游 DNS 服务器（国内） + 白名单规则（#）+ 黑名单规则（国外DNS）
> 
>     4. `#` 意为使用默认上游 DNS 服务器

那有什么办法不使用默认上游 DNS 服务器，就是只有 黑名单规则（国外DNS）+ 白名单规则（国内dns）

**Comment by hezhijie0327** [comment]
理论上屏蔽掉 `[GenerateDefaultUpstream](https://github.com/hezhijie0327/GFWList2AGH/blob/81a54589f6e9458f53711a16e05997fa5d2479da/release.sh#L155)` 即可

**Comment by Potterli20** [comment]
到时候看看，你的test的脚本
