### ISSUE TITLE
上游写这么多规则，不影响查询效率吗？

### ISSUE THREAD

**Issue by hiddow** [hezhijie0327/GFWList2AGH#2]
不太清楚，想了解一下

**Comment by hezhijie0327** [comment]
不影响查询，但运行加载时间会变长，这是我服务器上的一周的数据。
![Xnip2020-08-27_14-15-52](https://user-images.githubusercontent.com/58100052/91399132-0076fa80-e870-11ea-853d-e6c1f8179054.jpg)

**Comment by hezhijie0327** [comment]
![Xnip2020-08-27_14-18-51](https://user-images.githubusercontent.com/58100052/91399276-49c74a00-e870-11ea-832c-f6d1e9f10df3.jpg)
![Xnip2020-08-27_14-18-58](https://user-images.githubusercontent.com/58100052/91399279-4a5fe080-e870-11ea-8734-201e006c19b2.jpg)

**Comment by hiddow** [comment]
嗯，我看单独日志，解析速度确实没有受到影响。你有碰到过，使用Chrome打开安全的DNS选项有些网站会打开异常的慢，或者打开不开的情况吗？

**Comment by hiddow** [comment]
而且我看现在用的是gfwlist2agh_combine.txt这个列表，这里把国内的域名也加进来了，这种和之前的只加海外的域名，国内其他的都走上游的两个DNS有什么区别呢？

**Comment by hezhijie0327** [comment]
1. 这个有遇到过，通常都是上游 DNS 返回 SERVFAIL 值导致的；DNSPod 的 DoH/DoT 有时会有这种现象
2. 少数情况下（国内有CDN时），fonts.googleapis.com 被 googleapis.com 规则抢答，fonts.googleapis.com 在国内有 CDN；在 gfwlist2agh_gfwlist.txt 中会被海外 DNS 抢答。

**Comment by hiddow** [comment]
![image](https://user-images.githubusercontent.com/8944374/91409228-bd208a00-e877-11ea-9f40-d6a29b5c435f.png)
但是这两个不是国内正常的域名吗？我的理解是只要把后面两个bind 国内的DNS，合并到gfwlist2agh_combine.txt 这个列表就行了

**Comment by hezhijie0327** [comment]
1. 意思是精简 gfwlist2agh_combine.txt 规则是吗？
2. 后两个仅仅只是 Apple 和 Google 的规则，在前两个中还存在 Microsoft 等；仅合并后两个的话效果可能会打折扣。如果可以的话你可以手动删除前两条源，生成后测试一下。
3. 当前因为有 [hezhijie0327/DHDB](https://github.com/hezhijie0327/DHDb) 检测无效域名，至少能保证当前规则内的域名都是有效的，已经过删减。

**Comment by hiddow** [comment]
多谢解答！
