### ISSUE TITLE
分流问题

### ISSUE THREAD

**Issue by Atroc-0625** [hezhijie0327/GFWList2AGH#21]
cdn.jsdelivr.net，这个三级域名在国内有cdn，二级域名也在国内备案，但是走国外解析了。

**Comment by hezhijie0327** [comment]
1. 这是 `DHDb` 犯下的 `CDN` 判定错误，待重建完成后进行复查
2. 现已在本项目的 `data` 文件夹中修正，后续将由 `DHDb` 修正
