### ISSUE TITLE
手动删除，增加域名问题

### ISSUE THREAD

**Issue by Atroc-0625** [hezhijie0327/GFWList2AGH#24]
!mzstatic.com
已经在data_gfwlist.txt 排除此域名，还是会添加进规则内。

**Comment by hezhijie0327** [comment]
已定位

**Comment by Atroc-0625** [comment]
应该把手动增删设置为强制，手动为最信任。

**Comment by Atroc-0625** [comment]
你好，问题还是没有修复，!mzstatic.com，还是在走国外进行解析了。

**Comment by hezhijie0327** [comment]
请将自定义列表添入 `release.sh` 中的 [`gfwlist2agh_custom_cnacc`](https://github.com/hezhijie0327/GFWList2AGH/blob/2e07e0f4c0eaed822f46fc43a56649747a1cdd0a/release.sh#L34) 及 [`gfwlist2agh_custom_gfwlist`](https://github.com/hezhijie0327/GFWList2AGH/blob/2e07e0f4c0eaed822f46fc43a56649747a1cdd0a/release.sh#L37) 数组中后重试

**Comment by hezhijie0327** [comment]
如果愿意的话，可以将你的列表合并入主分支

**Comment by Atroc-0625** [comment]
已经加入，测试无效。

**Comment by hezhijie0327** [comment]
本地测试，有效，已删除 `mzstatic.com`

<img width="1147" alt="截图 2021-03-16 15 52 16" src="https://user-images.githubusercontent.com/58100052/111274213-b1f44680-866f-11eb-89f6-0a24fdb94880.png">

**Comment by Atroc-0625** [comment]
好的，我调整一下。

**Comment by Atroc-0625** [comment]
已经好了，谢谢。
