### ISSUE TITLE
域名分流

### ISSUE THREAD

**Issue by Atroc-0625** [hezhijie0327/GFWList2AGH#25]
www.apple.com.cn
此域名在国内有备案，但是被加入在GFW内，要强制排除一下。

**Comment by hezhijie0327** [comment]
Fixed.

**Comment by Atroc-0625** [comment]
感觉在gfwlist强制去除了就可以吧，没必要在cnacc立马在强制添加，因为没有匹配到的域名规则不是会走默认上游吗？

**Comment by hezhijie0327** [comment]
在黑名单模式中确实如此，但在白名单中该域名将默认走国外

**Comment by Atroc-0625** [comment]
> 在黑名单模式中确实如此，但在白名单中该域名将默认走国外

确实如此，不过还是黑名单模式会比较好，话说www.apple.com.cn为什么会被加入到gfwlist中

**Comment by hezhijie0327** [comment]
苹果的所有域名如果通过目前的检测手段（DNS 记录）都比较妖，有空再研究下

**Comment by Atroc-0625** [comment]
> 苹果的所有域名如果通过目前的检测手段（DNS 记录）都比较妖，有空再研究下

可以做个优先级处理吗？felixonmars的apple规则如果存在，felixonmars的规则作为第一。

**Comment by hezhijie0327** [comment]
行，可能要稍微晚几天，最近有点忙

**Comment by Atroc-0625** [comment]
> 行，可能要稍微晚几天，最近有点忙

好的，辛苦辛苦。这样就不着急处理检测手段的这个问题，因为apple/google，确实妖。

**Comment by Atroc-0625** [comment]
刚刚更新的，felixonmars的规则会高于手动的cnacc吗？应该手动写的列表优先级最高。

**Comment by hezhijie0327** [comment]
目前为同等级

**Comment by Atroc-0625** [comment]
> 目前为同等级

应该手动为最高优先级。手动永远都是最信任。

**Comment by hezhijie0327** [comment]
1. 优先级：强制移除 > 强制添加（felixonmars） > 常规添加
2. `felixonmars` 默认作为强制添加，但强制移除永远是最优先

**Comment by Atroc-0625** [comment]
是否常规添加这个可以去除，感觉没什么必要，只需要添加和移除，都为(强制)

**Comment by hezhijie0327** [comment]
1. 为了确保 `felixonmars` 内规则不被 `DHDb` 移除无效域，只能选择 `强制添加`
2. 强制移除优先级永远大于添加，所以人工校验的优先级和过去没有差别

**Comment by Atroc-0625** [comment]
> 1. 为了确保 `felixonmars` 内规则不被 `DHDb` 移除无效域，只能选择 `强制添加`
> 2. 强制移除优先级永远大于添加，所以人工校验的优先级和过去没有差别
> 3. 这次改动同时调整 `GFWList` 的优先级（ `人工` > `felixonmars` > `DHDb 无效列表` > `CNACC` > `GFWList`)

1.只是觉得常规添加这个可以去除，就使用强制添加和强制移除即可。
2.现在`GFWList` 的优先级（ `人工` > `felixonmars` > `DHDb 无效列表` > `CNACC` > `GFWList`)
那CNACC的优先级也是一样吗？还是CNACC就是会比GFWList优先。

**Comment by hezhijie0327** [comment]
均为相同优先级

**Comment by Atroc-0625** [comment]
> 均为相同优先级

紧急问题：googlevideo.com竟然会出现的CNACC列表内。导致youtube视频走了国内解析。

**Comment by Atroc-0625** [comment]
redirector.googlevideo.com这个也在CNACC,是什么问题导致？

**Comment by Atroc-0625** [comment]
google.com 也走到CNACC内了。

**Comment by hezhijie0327** [comment]
> google.com 也走到CNACC内了。

对于这个问题，是由于 LITE 列表建立过程中出现的异常

> redirector.googlevideo.com这个也在CNACC,是什么问题导致？

1. 由于海外`阿里 DNS` 解析结果未被污染，结合 `Google DNS` 的结果分析后，由 `DHDb` 分类为 `CDN` 
2. 目前解决方案为：`人工修改`

> 紧急问题：googlevideo.com竟然会出现的CNACC列表内。导致youtube视频走了国内解析。

是由以上域名存在 CNACC 中被 LITE 列表所创建

**Comment by hezhijie0327** [comment]
Fixed: 4e89be74717b83732d089e576ea6ffc9351e9de5

**Comment by Atroc-0625** [comment]
LITE 列表 是否解决

**Comment by hezhijie0327** [comment]
1. 以上问题已解决
2. 移除常规添加
3. `人工修改` 优先级大于一切列表

**Comment by Atroc-0625** [comment]
有看到常规添加/移除已经去除，辛苦。LITE列表是什么？

**Comment by hezhijie0327** [comment]
1. `LITE` 即仅二级域名规则
2. 目前由于人工修改规则优先级的更改，若需对列表进行增删会造成两次修改，近日会对规则进行优化，例如（`!@` / `@!`）同时对双列表进行增删操作

**Comment by Atroc-0625** [comment]
> 1. `LITE` 即仅二级域名规则
> 2. 目前由于人工修改规则优先级的更改，若需对列表进行增删会造成两次修改，近日会对规则进行优化，例如（`!@` / `@!`）同时对双列表进行增删操作

redirector.googlevideo.com 没有被污染可以移除GFW,你指的双列表增删操作的意思是把cnacc和gfwlist进行合并吗？

**Comment by Atroc-0625** [comment]
已经提交 #26

**Comment by hezhijie0327** [comment]
\# (@@@) | 向 C 及 G 列表添加域名
`(@@@)example.org`

\# (!!!) | 向 C 及 G 列表移除域名
`(!!!)example.org`

\# (@%@) | 仅向 C 列表添加域名
`(@%@)example.org`

\# (!%!) | 仅向 C 列表移除域名
`(!%!)example.org`

\# (@&@) | 仅向 G 列表添加域名
`(@&@)example.org`

\# (!&!) | 仅向 G 列表移除域名
`(!&!)example.org`

\# (@%!) | 向 C 列表添加域名并将其从 G 列表中移除
`(@%!)example.org`

\# (!%@) | 向 C 列表移除域名并将其从 G 列表中添加
`(!%@)example.org`

\# (@&!) | 向 G 列表添加域名并将其从 C 列表中移除
`(@&!)example.org`

\# (!&@) | 向 G 列表移除域名并将其从 C 列表中添加
`(!&@)example.org`

**Comment by Atroc-0625** [comment]
> # (@@@) | 向 C 及 G 列表添加域名
> `(@@@)example.org`
> 
> # (!!!) | 向 C 及 G 列表移除域名
> `(!!!)example.org`
> 
> # (@%@) | 仅向 C 列表添加域名
> `(@%@)example.org`
> 
> # (!%!) | 仅向 C 列表移除域名
> `(!%!)example.org`
> 
> # (@&@) | 仅向 G 列表添加域名
> `(@&@)example.org`
> 
> # (!&!) | 仅向 G 列表移除域名
> `(!&!)example.org`
> 
> # (@%!) | 向 C 列表添加域名并将其从 G 列表中移除
> `(@%!)example.org`
> 
> # (!%@) | 向 C 列表移除域名并将其从 G 列表中添加
> `(!%@)example.org`
> 
> # (@&!) | 向 G 列表添加域名并将其从 C 列表中移除
> `(@&!)example.org`
> 
> # (!&@) | 向 G 列表移除域名并将其从 C 列表中添加
> `(!&@)example.org`

有看到，有点复杂了，怕以后自定义会写错

**Comment by hezhijie0327** [comment]
1. 常规情况使用 `(@%!)` 及 `(@&!)` 即可
2. 这只是列出所有能识别的自定义规则

**Comment by Atroc-0625** [comment]
> * 常规情况使用 `(@%!)` 及 `(@&!)` 即可
> * 这只是列出所有能识别的自定义规则

好的，稍后我看下有什么问题。请看一下 #26

**Comment by hezhijie0327** [comment]
1. 对于 `redirector.googlevideo.com` 域名，属于特别情况，即检测为 `CDN` 但实际情况为污染状态
2. 由于海外使用 `阿里 DNS` 解析结果未被污染，但在国内仍属于污染状态，已在 [data_modify.txt](https://github.com/hezhijie0327/GFWList2AGH/blob/source/data/data_modify.txt) 中修正结果，故 #26 将不收录

**Comment by hezhijie0327** [comment]
Close. https://github.com/hezhijie0327/GFWList2AGH/commit/e6efa21c7c3d2a62c7af50aac5d7a5879b2390f0
