### ISSUE TITLE
软路由adguardhome如何使用？

### ISSUE THREAD

**Issue by da-gongren** [hezhijie0327/GFWList2AGH#3]
安装在软路由上的 adguardhome 如何使用？

**Comment by hezhijie0327** [comment]
可以尝试使用 WinSCP 将 gfwlist2agh_combine.txt 文件存放入相应文件夹，再编辑 adguardhome 根目录下的 AdGuardHome.yaml，将其中的 “upstream_dns_file” 键值更改为存放 gfwlist2agh_combine.txt 文件的路径，如“upstream_dns_file: /opt/adguardhome/conf/gfwlist2agh_combine.txt”。保存后重启 adguardhome 进程。
<img width="569" alt="截图 2020-12-10 17 02 10" src="https://user-images.githubusercontent.com/58100052/101750065-79d9e680-3b09-11eb-95c6-cf833e9a077a.png">

**Comment by hezhijie0327** [comment]
如果此操作过于繁杂，我稍后可以将针对于 UI 界面版的规则输出到相应文件 （暂定 gfwlist2agh_cnacc_ui.txt / gfwlist2agh_combine_ui.txt / gfwlist2agh_gfwlist_ui.txt）

**Comment by hezhijie0327** [comment]
> 如果此操作过于繁杂，我稍后可以将针对于 UI 界面版的规则输出到相应文件 （暂定 gfwlist2agh_cnacc_ui.txt / gfwlist2agh_combine_ui.txt / gfwlist2agh_gfwlist_ui.txt）

我忘了，当前版本的规则能直接适用于 UI 界面，您可以直接将其复制并粘贴进 “上游 DNS 服务器” 中
<img width="1212" alt="截图 2020-12-10 17 10 03" src="https://user-images.githubusercontent.com/58100052/101750868-90cd0880-3b0a-11eb-9ea6-49c89f483eeb.png">

**Comment by da-gongren** [comment]
感谢，刚接触这个不太懂。

现在的问题是，我上游的dns是Google的，导致国内的域名很多都解析成了香港的IP，网页打开很慢，使用 `gfwlist2agh_combine.txt` 这个文件可以解决嘛？

**Comment by da-gongren** [comment]
> > 如果此操作过于繁杂，我稍后可以将针对于 UI 界面版的规则输出到相应文件 （暂定 gfwlist2agh_cnacc_ui.txt / gfwlist2agh_combine_ui.txt / gfwlist2agh_gfwlist_ui.txt）
> 
> 我忘了，当前版本的规则能直接适用于 UI 界面，您可以直接将其复制并粘贴进 “上游 DNS 服务器” 中
> <img alt="截图 2020-12-10 17 10 03" width="1212" src="https://user-images.githubusercontent.com/58100052/101750868-90cd0880-3b0a-11eb-9ea6-49c89f483eeb.png">

嗯嗯，刚刚看了您这个文章了 https://www.zhijie.online/resources/personal_projects/GFWList2AGH/page.html

**Comment by hezhijie0327** [comment]
目前我用下来的体验来讲，能解决大部分问题，如果在体验中出现有什么网站误被判定使用 gfwlist_dns（Google / OpenDNS） 的话可以提出 issues，我可以将其添加进白名单。

**Comment by da-gongren** [comment]
![image](https://user-images.githubusercontent.com/51149477/101752966-10f46d80-3b0d-11eb-80fc-9fd0c7cfda6d.png)
这三个有啥区别？

**Comment by da-gongren** [comment]
@hezhijie0327 
![image](https://user-images.githubusercontent.com/51149477/101753046-2a95b500-3b0d-11eb-8b39-ed6be3a6d47c.png)
好像是不错，国内的走 direct 了。

**Comment by hezhijie0327** [comment]
可以理解为 白名单模式 / 黑名单模式 / 混合模式（修正黑名单中可能存在的白名单规则，如：||googleapis.com 和 ||fonts.googleapis.com，fonts.googleapis.com 在国内有 CDN，则应走国内 DNS 而不是使用 国外 DNS 进行解析）

**Comment by hezhijie0327** [comment]
combine 更适合日常使用，规则比较全面

**Comment by da-gongren** [comment]
> 可以理解为 白名单模式 / 黑名单模式 / 混合模式（修正黑名单中可能存在的白名单规则，如：||googleapis.com 和 ||fonts.googleapis.com，fonts.googleapis.com 在国内有 CDN，则应走国内 DNS 而不是使用 国外 DNS 进行解析）

那这个分流是怎么走的呢？

**Comment by hezhijie0327** [comment]
开启 “并行查询” 并以 gfwlist2agh_combine.txt 为例：
1. 当域名规则在 gfwlist 但不在 cnacc 中时，则走 https://doh.opendns.com:443/dns-query 和 tls://dns.google:853 进行查询（如：googleapis.com）
2. 当域名规则在 gfwlist 但其子域名在 cnacc 中时，则走 tls://dns.alidns.com:853 和 tls://dns.pub:853 进行查询（如：fonts.googleapis.com）
3. 当域名规则不在 gfwlist 但在 cnacc 中时，则走 tls://dns.alidns.com:853 和 tls://dns.pub:853 进行查询（如：www.baidu.com）
4. 当域名不在 gfwlist 也不在 cnacc 中时，则走 https://dns.alidns.com:443/dns-query 和 https://dns.pub:443/dns-query 进行查询（如：www.zhijie.online）

**Comment by da-gongren** [comment]
@hezhijie0327 
![image](https://user-images.githubusercontent.com/51149477/101783202-efa77780-3b34-11eb-97d5-504abe2e7a37.png)zhe那这两个是干啥的

**Comment by hezhijie0327** [comment]
> 4. 当域名规则不在 gfwlist 也不在 cnacc 中时，则走 https://dns.alidns.com:443/dns-query 和 https://dns.pub:443/dns-query 进行查询（如：www.zhijie.online）

**Comment by da-gongren** [comment]
腾讯的 `dot` [官网](https://www.dnspod.cn/Products/Public.DNS) 改了

**Comment by hezhijie0327** [comment]
虽然目前看来 dns.pub 和 doh.pub 指向的服务器地址为同一个，但现本项目中 DoH 及 DoT 地址均已更改为 doh.pub
<img width="737" alt="截图 2020-12-10 22 27 51" src="https://user-images.githubusercontent.com/58100052/101784867-09e25500-3b37-11eb-949e-a1badf1f3688.png">
<img width="499" alt="截图 2020-12-10 22 28 25" src="https://user-images.githubusercontent.com/58100052/101784868-0b138200-3b37-11eb-880b-0b30b07acb0f.png">

**Comment by da-gongren** [comment]
issue 其实可以不用关，也许有人跟我一样呢，不懂用。这个还是挺好的，用了这几天下来，体验挺好👍

**Comment by hezhijie0327** [comment]
好，我将此 issue 置顶😊

**Comment by 1379** [comment]
@hezhijie0327 感谢作者的贡献！使用体验非常nice👍。不过现在的目录和文件命名好像变了，
![image](https://user-images.githubusercontent.com/34785043/111024120-dbb33080-8417-11eb-9184-694e8f27054e.png)
这些都是什么意思，我应该使用哪个呢🤣

**Comment by hezhijie0327** [comment]
1. 通常来讲非特殊需求，使用 `blacklist_full.txt` 即可
2. `*_lite.txt` 仅精确到二级域名（`example.org`）

**Comment by tty228** [comment]
做了一个简陋的分流管理 luci
https://github.com/tty228/luci-app-adguardhome

**Comment by 4thanks** [comment]
> 做了一个简陋的分流管理 luci 上传格式限制，请解压 [luci-app-adguardhome_1.9-11_all.zip](https://github.com/hezhijie0327/GFWList2AGH/files/8598190/luci-app-adguardhome_1.9-11_all.zip)

@tty228 可以考虑一下smartdns分流管理 luci？直接套用一下这个简陋模块也就够了
