### ISSUE TITLE
导入到adhome 无法保存

### ISSUE THREAD

**Issue by mfblog** [hezhijie0327/GFWList2AGH#36]
![image](https://user-images.githubusercontent.com/56717860/148554755-5ce86453-8c3a-4270-9d74-9917c942e047.png)
![image](https://user-images.githubusercontent.com/56717860/148554777-cbb085e6-eca9-462a-81d7-6df4a429554e.png)

**Comment by hezhijie0327** [comment]
内容过大，更改 AdGuardHome.yaml 配置文件中的 `upstream_dns_file` 参数，使用外部配置文件导入规则
