### ISSUE TITLE
列表可以只保留域名即可

### ISSUE THREAD

**Issue by thb007** [hezhijie0327/GFWList2AGH#4]
例如转发域名“zzz.healthsection.xyz”，只需要保留“healthsection.xyz”，一级域名即可，这样可以大量减少属性，提高效率。

**Comment by thb007** [comment]
这条转发域名"healthgovt.xyz","healthsection.xyz"重复了好几个

```
[/zy.etowns.net/zynamics.com/zynews.com/zyns.com/zyxel.com/zyzg.us/zz383.net/zz757.net/zzcartoon.com/zzcloud.me/zzju.22.4irc.com/zzp.familyhealth.xyz/zzq.familyhealth.xyz/zzr.familyhealth.xyz/zzs.comhealth.xyz/zzs.healthorg.xyz/zzsolt.hu/zzt.familyhealth.xyz/zzt.healthorg.xyz/zzu.healthorg.xyz/zzu.healthsection.xyz/zzux.com/zzv.healthgovt.xyz/zzw.healthsection.xyz/zzy.dnsmail.xyz/zzy.healthorg.xyz/zzy.healthsection.xyz/zzz.healthsection.xyz/zzz5595.com/]tls://dns.google:853

```

**Comment by hezhijie0327** [comment]
1. 这个我也考虑过精简规则，但是基于目前对域名是否存活的[检测机制](https://github.com/hezhijie0327/DHDb)可能不适用于所有域名。假设 example.org 的 A 或 AAAA 记录不存在，则会判定为 dead 并从规则中移除。
2. 同 #2 至少通过 [hezhijie0327/DHDb](https://github.com/hezhijie0327/DHDb) 已剔除无效域名来精简规则文件
3. 根据日常使用来讲，目前未发现规则数会对效率产生太大的影响，以下是我 VPS 的截图
<img width="567" alt="截图 2020-12-18 22 58 55" src="https://user-images.githubusercontent.com/58100052/102628493-b8fcdd00-4184-11eb-87ec-c5e254206e70.png">
<img width="582" alt="截图 2020-12-18 22 59 05" src="https://user-images.githubusercontent.com/58100052/102628498-ba2e0a00-4184-11eb-9013-53ad2a179911.png">
4. 如果某条域名存在大量规则冗余且在人工验证后其75%以上的子域名均被污染再考虑将规则合并为一级域名

**Comment by thb007** [comment]
> 2\. test.example.

  如果我只想保留一级域名呢？怎么改sh执行文件？我感觉我只需要一级域名就好了。

**Comment by hezhijie0327** [comment]
已支持生成仅一级域名规则
1. 黑名单模式（[gfwlist2agh_blacklist.txt](https://source.zhijie.online/GFWList2AGH/main/gfwlist2agh_blacklist.txt)）
2. 精简黑名单模式（[gfwlist2agh_blacklist_lite.txt](https://source.zhijie.online/GFWList2AGH/main/gfwlist2agh_blacklist_lite.txt)）
3. 白名单模式（[gfwlist2agh_whitelist.txt](https://source.zhijie.online/GFWList2AGH/main/gfwlist2agh_whitelist.txt)）
4. 精简白名单模式（[gfwlist2agh_whitelist_lite.txt](https://source.zhijie.online/GFWList2AGH/main/gfwlist2agh_whitelist_lite.txt)）
*. 黑名单模式，在规则外默认走国内 DNS；白名单模式，在规则外默认走海外 DNS

**Comment by thb007** [comment]
> 已支持生成仅一级域名规则
> 
> 1. 黑名单模式（[gfwlist2agh_blacklist.txt](https://source.zhijie.online/GFWList2AGH/main/gfwlist2agh_blacklist.txt)）
> 2. 精简黑名单模式（[gfwlist2agh_blacklist_lite.txt](https://source.zhijie.online/GFWList2AGH/main/gfwlist2agh_blacklist_lite.txt)）
> 3. 白名单模式（[gfwlist2agh_whitelist.txt](https://source.zhijie.online/GFWList2AGH/main/gfwlist2agh_whitelist.txt)）
> 4. 精简白名单模式（[gfwlist2agh_whitelist_lite.txt](https://source.zhijie.online/GFWList2AGH/main/gfwlist2agh_whitelist_lite.txt)）
>    *. 黑名单模式，在规则外默认走国内 DNS；白名单模式，在规则外默认走海外 DNS

谢谢
