### ISSUE TITLE
请教 upstream_dns_file 每行的具体意义

### ISSUE THREAD

**Issue by hellodword** [hezhijie0327/GFWList2AGH#41]
我用的是 `whitelist_full_combine.txt`，简化一下就是

```
https://doh.opendns.com:443/dns-query
[/zzz.healthsection.xyz/zzz36.net/]#
[/zzzzmall.com/zzzzzz.me/]https://doh.pub:443/dns-query
```

第一行是默认的 DNS，第三行是指定用 `https://doh.pub:443/dns-query` 来解析给定的域名，第二行的 `#` 是单指第一行还是指 AdGuardHome 默认的 DNS ？

```
tls://8.8.4.4
https://doh.opendns.com:443/dns-query
[/zzz.healthsection.xyz/zzz36.net/]#
[/zzzzmall.com/zzzzzz.me/]https://doh.pub:443/dns-query
```

例如这样配置，并且 `AdGuardHome.yaml` 中配置 `all_server: true`（也就是并行请求）， `zzz36.ne` 的解析会是怎么样的流程呢？

**Comment by hezhijie0327** [comment]
以这个配置文件为例
```
tls://8.8.4.4
https://doh.opendns.com:443/dns-query
[/zzz.healthsection.xyz/zzz36.net/]#
[/zzzzmall.com/zzzzzz.me/]https://doh.pub:443/dns-query
```
1. 当解析 `zzzzmall.com` 或 `zzzzmall.com` 时，由 `https://doh.pub:443/dns-query` 处理
2. 当解析 `zzz.healthsection.xyz`、`zzz36.net` 或不在配置文件中特殊指定的域名时，由 `tls://8.8.4.4` 及 `https://doh.opendns.com:443/dns-query` 处理，即 `#` 为走默认 DNS 地址

**Comment by hellodword** [comment]
> 以这个配置文件为例
> 
> ```
> tls://8.8.4.4
> https://doh.opendns.com:443/dns-query
> [/zzz.healthsection.xyz/zzz36.net/]#
> [/zzzzmall.com/zzzzzz.me/]https://doh.pub:443/dns-query
> ```
> 
> 1. 当解析 `zzzzmall.com` 或 `zzzzmall.com` 时，由 `https://doh.pub:443/dns-query` 处理
> 2. 当解析 `zzz.healthsection.xyz`、`zzz36.net` 或不在配置文件中特殊指定的域名时，由 `tls://8.8.4.4` 及 `https://doh.opendns.com:443/dns-query` 处理，即 `#` 为走默认 DNS 地址

非常感谢，那我多加几个默认的 upstream， `https://doh.opendns.com:443/dns-query` 我这里偶尔会请求失败

**Comment by tanst** [comment]
有个疑问：
带 `#` 的列表本身就是走默认 DNS 服务器了，没必要再写上去了吧
