### ISSUE TITLE
Domain Remove Request

### ISSUE THREAD

**Issue by BlueSkyXN** [hezhijie0327/GFWList2AGH#48]
Hello, I am the owner of blueskyxn.com and 000714.xyz.
 Due to the recent firewall of mainland China interfering with my transit node (forwarding overseas data sources to the CDN in mainland China through mainland optimized lines), some accesses are unstable.
 Coupled with the recent increase in the cost of traffic in mainland China, I hope to remove all my domains from the mainland China optimization list.

 The list of domain names is as follows (including all subdomains)
 blueskyxn.com
 000714.xyz

In addition, if you know of other similar projects, I also hope to introduce them so that I can deal with them further.

**Comment by hezhijie0327** [comment]
Closed. f88ff92934dd91b001d08cb8593879c88032d2c8

**Comment by hezhijie0327** [comment]
Fork 后自行移除注释 `#`
https://github.com/hezhijie0327/GFWList2AGH/blob/1002f1a83479080db17571eb16ec99ceec9850bd/data/data_modify.txt#L111-L113
