### ISSUE TITLE
ubuntu解析到了美国

### ISSUE THREAD

**Issue by weifancloud** [hezhijie0327/GFWList2AGH#5]
很奇怪 我的 `ubuntu`、`centos` 异常了
apt 安装软件很慢，最后发现时 `dns` 的问题，阿里的源解析到了美国，测试了下京东、百度也都解析到了美国。而 `windows`、`deepin` 却是正常的
![image](https://user-images.githubusercontent.com/57950591/102801096-b5b95980-43ef-11eb-9b81-1f49c911e28c.png)

**Comment by hezhijie0327** [comment]
上游文件用了哪一个？我这边使用 combine + 开启 EDNS 后解析结果正常
<img width="567" alt="截图 2020-12-22 01 17 09" src="https://user-images.githubusercontent.com/58100052/102803642-84428d00-43f3-11eb-94a1-52cfe0422597.png">
<img width="950" alt="截图 2020-12-22 01 19 42" src="https://user-images.githubusercontent.com/58100052/102803801-ca97ec00-43f3-11eb-82a4-48a373ac9918.png">

**Comment by weifancloud** [comment]
使用的是 `gfwlist2agh_combine.txt` 

![image](https://user-images.githubusercontent.com/57950591/102850554-bf28dd00-4454-11eb-81af-67016c68dba1.png)
 
![image](https://user-images.githubusercontent.com/57950591/102850679-f8614d00-4454-11eb-8913-06d5eac5f8c2.png)

看日志，分流是成功了，`dns` 的问题？

**Comment by hezhijie0327** [comment]
AGH 中 EDNS 开了吗？我在我的VPS上无法复现此问题。可以尝试使用 `https://ifconfig.zhijie.online/ip` 获取 IP 地址，查看是否与 1 处前缀一致，如：`222.64.12.0/24/24`。
<img width="486" alt="截图 2020-12-22 13 08 01" src="https://user-images.githubusercontent.com/58100052/102851490-ed0f2100-4456-11eb-847d-799b9747552d.png">
<img width="768" alt="截图 2020-12-22 13 04 59" src="https://user-images.githubusercontent.com/58100052/102851493-ef717b00-4456-11eb-94f0-abb29a0337e8.png">

**Comment by weifancloud** [comment]
查到问题，是EDNS。谢谢你的解答
