### ISSUE TITLE
新增国内，国外域名列表

### ISSUE THREAD

**Issue by Atroc-X** [hezhijie0327/GFWList2AGH#51]
国内：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/China/China_Domain.list
国外：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Proxy/Proxy_Domain.list

**Comment by Atroc-X** [comment]
是代理软件的规则，这个是收集整合的域名列表规则，全面程度不错。

**Comment by hezhijie0327** [comment]
Closed. 5d842a45a200779b0a9115e04a179bccf2e68476
