### ISSUE TITLE
打扰大佬了，请问full与lite的具体区别是什么，lite精简了些啥，full多了些啥，以及lite跟full对agh的性能影响区别大不大。

### ISSUE THREAD

**Issue by Moexin** [hezhijie0327/GFWList2AGH#6]
打扰大佬了，请问full与lite的具体区别是什么，lite精简了些啥，full多了些啥，以及lite跟full对agh的性能影响区别大不大。

**Comment by hezhijie0327** [comment]
从性能上来讲两者几乎没区别，原先只有 full 列表，后来由于 #4 的需求才将 lite 放出。
lite 列表中仅保留了一级域名，相比于 full 在分流的体验上尚有待考察。即：
full 列表中：`fonts.googleapis.com` `translate.googleapis.com` ...
lite 列表中：`googleapis.com` （仅一级域名）

**Comment by Moexin** [comment]
了解了，感谢解惑，找了一圈就只有大佬维护的规则最好用，希望大佬能一直维护下去，在国内这个复杂的网络环境，规则分流目前是我体验到的最优解，再次感谢作者能提供这么好的项目，衷心感谢！
