### ISSUE TITLE
哦吼，怎么又改了

### ISSUE THREAD

**Issue by da-gongren** [hezhijie0327/GFWList2AGH#7]
老哥，现在推荐用哪个文件呢，白名单还是黑名单呀

**Comment by hezhijie0327** [comment]
1. 主要是 #4 的需求，我把整套流程大改了一下，以防下次再有类似需求时可以灵活创建
2. 白名单：规则外走国外 DNS；黑名单：规则外走国内 DNS
3. LITE 和 FULL 的区别在于，LITE 仅保留了一级域名 #4
4. “gfwlist2agh_blacklist_full.txt” 就是原来的 “gfwlist2agh_combine.txt”

**Comment by da-gongren** [comment]
@hezhijie0327 非常感谢👍
