### ISSUE TITLE
配置文件有问题

### ISSUE THREAD

**Issue by Atroc-0625** [hezhijie0327/GFWList2AGH#8]
国内域名和国外域名都在一起解析

**Comment by Atroc-0625** [comment]
https://raw.githubusercontent.com/hezhijie0327/GFWList2AGH/main/gfwlist2agh_whitelist_full.txt
最前面是国外DNS防止污染，中间[]域名出现/google.com/baidu.com/，国内国外域名都在里面，最后应该用国内dns解析。
正确的whitelist，应该是:
国外dns
[国内域名]国内dns

**Comment by Atroc-0625** [comment]
我在看了一下，不管是白名单模式，还是黑名单模式[]规则内都是有baidu.com/google.com

**Comment by Atroc-0625** [comment]
黑名单模式：
国内dns
[国外域名]国外dns

**Comment by hezhijie0327** [comment]
1. 问题已经找到了，来自上游规则 [Loyalsoldier/v2ray-rules-dat](https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/proxy-list.txt)
<img width="263" alt="截图 2020-12-31 10 32 14" src="https://user-images.githubusercontent.com/58100052/103391284-a191fc80-4b53-11eb-89f4-0fe839f3f6af.png">
2. 当前文件格式为：
    国内DNS
    [/国内域名/]国内DNS -> 此处DNS用 # 进行替代，即走默认值
    [/国外域名/]国外DNS
3. 那是否需要还原到以前那样的结构，如果需要我修改下生成脚本：
    国内DNS
    [/国外域名/]国外DNS

**Comment by Atroc-0625** [comment]
你好，需要的

**Comment by Atroc-0625** [comment]
因为我这边网络情况，只要用国外dns就不会有污染，所以需要。

**Comment by Atroc-0625** [comment]
国外dns
[国内域名]国内dns

**Comment by Atroc-0625** [comment]
国内dns
[国外域名]国外dns

**Comment by Atroc-0625** [comment]
[]规则内的域名匹配对应国家的dns

**Comment by hezhijie0327** [comment]
1. 已支持生成分离黑白名单规则
      黑名单模式（[gfwlist2agh_blacklist_full_split.txt](https://source.zhijie.online/GFWList2AGH/main/gfwlist2agh_blacklist_full_split.txt)）
      精简黑名单模式（[gfwlist2agh_blacklist_lite_split.txt](https://source.zhijie.online/GFWList2AGH/main/gfwlist2agh_blacklist_lite_split.txt)）
      白名单模式（[gfwlist2agh_whitelist_full_split.txt](https://source.zhijie.online/GFWList2AGH/main/gfwlist2agh_whitelist_full_split.txt)）
      精简白名单模式（[gfwlist2agh_whitelist_lite_split.txt](https://source.zhijie.online/GFWList2AGH/main/gfwlist2agh_whitelist_lite_split.txt)）
2. 修正 `translate.baidu.com` 异常出现在黑名单中 ca0c500

**Comment by Atroc-0625** [comment]
好的，谢谢。
[国外域名]国外dns/国外dns
怎么在规则域名后添加两个国外dns

**Comment by hezhijie0327** [comment]
这个[官方规则](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#specifying-upstreams-for-domains)中暂时不支持，但是有人已经提出类似 [GROUP](https://github.com/AdguardTeam/AdGuardHome/issues/2446) 的建议，后续如果上线将同步该功能，但相比于他提出的那种方式，我更偏向于你的想法但是分隔符最好不要是 “/” 毕竟 DoH 中也存在该符号，例如：`[/www.google.com/]https://doh.opendns.com:443/dns-query,tls://dns.google:853`

**Comment by Atroc-0625** [comment]
，符号确实比较符合。

**Comment by hezhijie0327** [comment]
我刚刚也在那提了一下，看官方怎么抉择了

**Comment by Atroc-0625** [comment]
提个小建议，增加README，介绍一下full,lite,split.

**Comment by Atroc-0625** [comment]
还有一个建议，如果我有一个A.COM是被污染的，我如何方便加入规则脚本内。

**Comment by hezhijie0327** [comment]
> 提个小建议，增加README，介绍一下full,lite,split.

我有空写一下


> 还有一个建议，如果我有一个A.COM是被污染的，我如何方便加入规则脚本内。

可以通过在 `data/data_gfwlist.txt` 中添加，或者开个 issue

**Comment by Atroc-0625** [comment]
好的，谢谢，先close了，感谢支持。

**Comment by Atroc-0625** [comment]
你好，打扰了，adguard.org这个域名可以加入在gfw内吗？

**Comment by hezhijie0327** [comment]
1. 刚刚测试了下 `adguard.org` 记录为空，目前[域名状态检测机制](https://github.com/hezhijie0327/DHDb)会将其排除
2. `local.adguard.org` 记录未被污染

**Comment by Atroc-0625** [comment]
thanks

**Comment by Atroc-0625** [comment]
域名:secgw-aserver-heyi.m.taobao.com.gds.alibabadns.com
这是观看ios APP 优酷抓到域名cdn，不在国内地址表中，所以优酷一直弹vpn的提示
添加alibabadns.com到国内地址表中即可。

**Comment by Atroc-0625** [comment]
不加入国内地址表，会解析到海外的cdn上。

**Comment by Atroc-0625** [comment]
![image](https://user-images.githubusercontent.com/37469514/103451034-b3150900-4cf9-11eb-91cf-039eb99b6e2c.png)
image.uc.cn也是一个阿里的cdn，

**Comment by Atroc-0625** [comment]
虽然alikunlun.com在国内域名表中，但还是会解析到香港cdn上

**Comment by Atroc-0625** [comment]
![image](https://user-images.githubusercontent.com/37469514/103451166-94177680-4cfb-11eb-9299-93294aed8bd2.png)
我fork您的项目，加入在这里，红色的添加在国内域名表内成功，绿色的添加在国内域名表内失败。

**Comment by hezhijie0327** [comment]
1. 以后还有类似的域名最好再开个新 issue
2. 失败的原因还是同上，检测机制不允许它加入
3. 近期设计个强制添加规则的方法，让这些域名能够绕开检测机制（暂定 `@example.org`）

**Comment by Atroc-0625** [comment]
好的，以后新问题开新的issue,不好意思
对的，很需要强制添加域名进去。

**Comment by hezhijie0327** [comment]
1. 已支持强制添加规则 `@example.org`
2. 已添加上述域名：`@alibabadns.com ` `@it-global.cn` `ssnm.xyz` `@global-ict.cn` `@global-idc.net` `uc.cn`

**Comment by Atroc-0625** [comment]
感谢。
